defmodule Rclex.Generators.TypeHash do
  @moduledoc """
  Reads REP-2011 type hashes from ROS-generated type description JSON files.

  The JSON contains the canonical hash generated by ROS. Reading it is
  intentional: hashing the source text directly is not REP-2011 compatible.
  """

  @spec type_hash(String.t(), String.t()) :: {:ok, String.t()} | {:error, atom() | tuple()}
  def type_hash(type_name, share_path) when is_binary(type_name) and is_binary(share_path) do
    with {:ok, path} <- description_path(type_name, share_path),
         {:ok, contents} <- File.read(path),
         {:ok, document} <- Jason.decode(contents),
         {:ok, hashes} <- fetch_hashes(document),
         {:ok, hash} <- find_hash(hashes, type_name) do
      {:ok, hash}
    else
      {:error, :enoent} -> {:error, :not_found}
      {:error, %Jason.DecodeError{}} -> {:error, :invalid_description}
      {:error, reason} -> {:error, reason}
    end
  end

  @spec type_hash!(String.t(), String.t()) :: String.t()
  def type_hash!(type_name, share_path) do
    case type_hash(type_name, share_path) do
      {:ok, hash} -> hash
      {:error, reason} -> raise ArgumentError, "failed to read type hash: #{inspect(reason)}"
    end
  end

  defp description_path(type_name, share_path) do
    case String.split(type_name, "/") do
      [package, kind, name] when kind in ["msg", "srv", "action"] ->
        path = Path.join([share_path, package, kind, "#{name}.json"])

        if File.exists?(path), do: {:ok, path}, else: {:error, :enoent}

      _ ->
        {:error, :invalid_type_name}
    end
  end

  defp fetch_hashes(%{"type_hashes" => hashes}) when is_list(hashes), do: {:ok, hashes}
  defp fetch_hashes(_document), do: {:error, :missing_type_hashes}

  defp find_hash(hashes, type_name) do
    case Enum.find(hashes, &(&1["type_name"] == type_name)) do
      %{"hash_string" => hash} when is_binary(hash) -> {:ok, hash}
      nil -> {:error, :type_hash_not_found}
      _entry -> {:error, :invalid_type_hash}
    end
  end
end
