name: ci-all_version

on: [push]

defaults:
  run:
    shell: bash

jobs:
  rclex_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertags: [latest, dashing-ex1.12.0-otp24.0.1, dashing-ex1.11.2-otp23.3.1, dashing-ex1.10.4-otp22.3.4, dashing-ex1.9.4-otp22.3.4, dashing-ex1.9.1-otp22.0.7, foxy-ex1.12.0-otp24.0.1, foxy-ex1.11.2-otp23.3.1]
    container: rclex/rclex_docker:${{ matrix.dockertags }}

    steps:
        - name: clone rclex
          uses: actions/checkout@v2
          with: 
            repository: rclex/rclex
            path: rclex
        - name: clone rclex_connection_tests
          uses: actions/checkout@v2
          with:
            repository: rclex/rclex_connection_tests
            path: rclex_connection_tests

        - name: mix compile
          run: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            cd rclex
            mix local.hex --force
            mix deps.get
            mix compile

        - name: mix format
          run: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            cd rclex
            mix format --check-formatted

        - name: mix credo
          run: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            cd rclex
            mix credo --all

        - name: mix test
          run: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            cd rclex
            mix test

        - name: connection tests
          run: | 
            source /opt/ros/${ROS_DISTRO}/setup.bash
            cd rclex_connection_tests
            ./run-all.sh

