on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  rclex_test:
    runs-on: ubuntu-latest
    container: rclex/rclex_docker:latest

    steps:
        # clone latest branch
        - name: clone
          uses: actions/checkout@v2
          with: 
            repository: rclex/rclex
            path: rclex
        - name: clone rclex_connection_tests
          uses: actions/checkout@v2
          with:
            repository: rclex/rclex_connection_tests
            path: rclex_connection_tests

        - name: mix test 
          run: |
            source /opt/ros/dashing/setup.bash
            cd rclex
            mix local.hex --force
            mix deps.get
            mix compile
            mix test

        - name: ros2 connection test
          run: | 
            source /opt/ros/dashing/setup.bash
            cd rclex_connection_tests
            ./entrypoint.sh

