name: ci-all_version

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  CI_on_PR:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertags: [latest, foxy-ex1.13.1-otp24.1.7, foxy-ex1.12.3-otp24.1.5, foxy-ex1.11.4-otp23.3.4, dashing-ex1.12.3-otp24.1.5, dashing-ex1.11.4-otp23.3.4, dashing-ex1.10.4-otp23.3.4, dashing-ex1.9.4-otp22.3.4.18]
    container: rclex/rclex_docker:${{ matrix.dockertags }}

    steps:
      - name: Checkout rclex repo
        uses: actions/checkout@v2
        with: 
          repository: rclex/rclex
          path: rclex
      - name: Checkout rclex_connection_tests repo
        uses: actions/checkout@v2
        with: 
          repository: rclex/rclex_connection_tests
          path: rclex_connection_tests
      
      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            rclex/deps
            rclex/_build
          key: ${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dockertags }}-mix-

      - name: Build dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: mix format
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix format --check-formatted

      - name: mix test
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix local.hex --force
          mix test

      - name: connection tests
        run: | 
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex_connection_tests
          ./run-all.sh
